# Generated by Django 5.1.2 on 2024-10-21 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('uploaded_files', models.JSONField(default=list)),
                ('messages', models.JSONField(default=list)),
            ],
        ),
    ]
