# Generated by Django 5.1.2 on 2024-10-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='id',
            new_name='thread_id',
        ),
    ]
