# Generated by Django 5.1.2 on 2024-10-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_rename_id_thread_thread_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='user_id',
            new_name='doctor_id',
        ),
    ]
