# Generated by Django 5.1.2 on 2024-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_rename_user_id_thread_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
